apps/forms/urls.py
from django.conf.urls import url
import apps.forms.views

urlpatterns = [
    url(r'^get/(?P<whois>[-\w]+)/$', apps.forms.views.form, name='form'),
]

ecommerce/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import apps.homepage.views
import ecommerce.views

urlpatterns = [
    url(r'^$', apps.homepage.views.homepage, name='homepage'),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/password_reset/$', auth_views.password_reset, name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'
    ),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^robots.txt', ecommerce.views.robots_txt, name='robots_txt'),
    url(r'^404/', ecommerce.views.page_404, name='page_404'),
    url(r'^thank-you/', ecommerce.views.thank_you_page, name='thank_you_page'),
    url(r'^contacts/', ecommerce.views.contact_page, name='contacts'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^forms/', include('apps.forms.urls', namespace='forms')),
    url(r'^catalog/', include('apps.catalog.urls', namespace='catalog')),
    url(r'^cart/', include('apps.order.urls', namespace='order')),
    url(r'^manage/', include('apps.manage.urls', namespace='manage')),
    url(r'^sitemap.xml$', ecommerce.views.sitemap, name='sitemap'),
    url(r'^(?P<slug>[-\w]+)/$', ecommerce.views.page, name='page'),
]

if settings and settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/forms/models.py
from django.db import models
from apps.helpers.models import LogMixin


class Call(LogMixin):
    name = models.CharField(max_length=100, verbose_name='Имя')
    phone = models.CharField(max_length=100, verbose_name='Телефон')

    class Meta():
        verbose_name = 'Заказ обратного звонка'
        verbose_name_plural = 'Заказ обратного звонка'

    def __str__(self):
        return '%s (%s)' % (self.phone, self.name)


class Feedback(LogMixin):
    name = models.CharField(max_length=100, verbose_name='Имя')
    phone = models.CharField(default='', max_length=100, blank=True, verbose_name='Телефон')
    email = models.EmailField(default='', blank=True, verbose_name='Email')
    message = models.TextField(default='', blank=True, verbose_name='Сообщение')

    class Meta():
        verbose_name = 'Форма обратной связи'
        verbose_name_plural = 'Форма обратной связи'

    def __str__(self):
        return self.email

apps/forms/admin.py
from django.contrib import admin
from apps.forms.models import *


class CallAdmin(admin.ModelAdmin):
    list_display = ('name', 'phone', 'created_at',)
    search_fields = ['name', 'phone']
    readonly_fields = ('updated_at', 'created_at',)


class FeedbackAdmin(admin.ModelAdmin):
    list_display = ('name', 'phone', 'email', 'created_at',)
    search_fields = ['name', 'phone', 'email']
    readonly_fields = ('updated_at', 'created_at',)


admin.site.register(Call, CallAdmin)
admin.site.register(Feedback, FeedbackAdmin)

apps/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'apps.forms'
    verbose_name = "Формы"

apps/forms/forms.py
from django import forms
from django.forms import ModelForm
from apps.forms.models import *
from apps.order.models import Order


class CallForm(ModelForm):
    class Meta:
        model = Call
        exclude = ['created_at', 'updated_at']


class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        exclude = ['created_at', 'updated_at']


class QuickOrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = [
            'created_at', 'updated_at', 'price',
            'length', 'uid', 'address', 'comment', 'email'
        ]

        widgets = {
            'phone': forms.TextInput(attrs={
                'autofocus': 'autofocus',
                'required': 'required',
                'placeholder': 'Номер телефона',
            }),
            'name': forms.TextInput(attrs={'placeholder': 'Ваше имя'}),
        }


class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ['created_at', 'updated_at', 'price', 'length', 'uid']

        widgets = {
            'phone': forms.TextInput(attrs={
                'autofocus': 'autofocus',
                'required': 'required',
                'placeholder': 'Номер телефона',
            }),
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email для уведомлений',
            }),
            'name': forms.TextInput(attrs={'placeholder': 'Ваше имя'}),
            'address': forms.Textarea(attrs={'placeholder': 'Адрес доставки'}),
            'comment': forms.Textarea(attrs={'placeholder': 'Комментарий'}),
        }

apps/forms/views.py
from django.http import Http404, HttpResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.template.response import TemplateResponse
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
from ecommerce.models import NotificationRecipients
from apps.forms.models import *
from apps.forms.forms import *
import json


@ensure_csrf_cookie
def form(request, whois):
    whois = whois.lower()
    form = None

    if whois == 'call':
        form = CallForm(request.POST)
    elif whois == 'feedback':
        form = FeedbackForm(request.POST)
    elif whois == 'quick-order':
        form = QuickOrderForm(request.POST)

    if form is None:
        raise Http404

    if request.method == 'POST':
        context = {
            'success': False,
        }

        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.save()

            names = {
                'call': 'Заказ обратного звонка',
                'feedback': 'Форма обратной связи'
            }

            if whois in names.keys():
                model_instance.form_name = names[whois]

                notification = render_to_string('forms/notification.html', {
                    'form': model_instance,
                })

                recipients = NotificationRecipients.objects.all()
                emails = list([nr.email.lower() for nr in recipients])
                send_mail(
                    subject='Обращение с сайта',
                    message=notification,
                    html_message=notification,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=emails,
                    fail_silently=False
                )
                context['success'] = True
        else:
            context['success'] = False
            context['errors-fields'] = form.errors.keys()

        return HttpResponse(json.dumps(context), content_type='application/json')
    else:
        content = TemplateResponse(request, 'forms/form.html', {'form': form, 'whois': whois})
        content = content.render()

        return HttpResponse(content.rendered_content)

templates/forms/form.html
{% if whois == "call" %}
    <div class="modal-form call js-modal-form" data-whois="call">
        <div class="modal-form__close js-modal-form__close"></div>
        <div class="modal-form__title">Заказ звонка</div>
        <div class="modal-form__note">Оставьте Ваш номер телефона и мы перезвоним!</div>

        <form action="{% url "forms:form" whois %}" method="POST" class="js-ajax-form">
            {% csrf_token %}

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-name js-required" name="{{ form.name.name }}" placeholder="Пожалуйста, представьтесь*">
            </div>

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-phone js-required" name="{{ form.phone.name }}" placeholder="Ваш телефон*">
            </div>
            <div class="modal-form__bottom">
                <span class="modal-form__button send js-modal-form__send-button">Жду звонка</span>
            </div>
        </form>
    </div>
{% elif whois == "quick-order" %}
    <div class="modal-form call js-modal-form" data-whois="call">
        <div class="modal-form__close js-modal-form__close"></div>
        <div class="modal-form__title">Быстрый заказ</div>
        <div class="modal-form__note">Оставьте Ваш номер телефона и мы перезвоним для уточнения деталей заказа.</div>

        <form action="/cart/save/" method="POST" class="js-ajax-form">
            {% csrf_token %}

            <input type="hidden" name="quick-order" value="yes">

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-phone js-required" name="{{ form.phone.name }}" placeholder="Телефон — обязательное поле">
            </div>

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-name" name="{{ form.name.name }}" placeholder="Как к вам обращаться?">
            </div>

            <div class="modal-form__bottom">
                <span class="modal-form__button send js-modal-form__send-button js-modal-form__submit">Оформить заказ</span>
            </div>
        </form>
    </div>
{% elif whois == "feedback" %}
    <div class="modal-form feedback js-modal-form" data-whois="feedback">
        <div class="modal-form__close js-modal-form__close"></div>
        <div class="modal-form__title">Форма обратной связи</div>

        <form action="{% url "forms:form" whois %}" method="POST" class="js-ajax-form">
            {% csrf_token %}

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-name js-required" name="{{ form.name.name }}" placeholder="Пожалуйста, представьтесь*">
            </div>

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-email js-required" name="{{ form.phone.email }}" placeholder="Ваш email (для ответа)*">
            </div>

            <div class="modal-form__row">
                <input type="text" class="modal-form__input js-phone" name="{{ form.phone.name }}" placeholder="Ваш телефон (по желанию)">
            </div>

            <div class="modal-form__row">
                <textarea class="modal-form__textarea js-message js-required" name="{{ form.message.name }}" placeholder="Напишите вопрос*"></textarea>
            </div>

            <div class="modal-form__bottom">
                <span class="modal-form__button send js-modal-form__send-button">Отправить</span>
            </div>
        </form>
    </div>
{% endif %}

templates/forms/notification.html
<div>
    Здравствуйте.
</div>

<div style="margin-top:8px;">
    Только что, {{ form.created_at|date:"d.m.Y" }} в {{ form.created_at|date:"H:i" }}, на Вашем сайте была заполнена форма "{{ form.form_name }}".
</div>

<div style="margin-top:16px;">
    Данные формы:
</div>

<div style="margin-top:8px;">
    <table align="left" valign="top" cellpadding="4" cellspacing="0" style="border-collapse:collapse; clear:both;">
        {% if form.name %}
            <tr>
                <td valign="top">Имя:</td>
                <td valign="top">{{ form.name }}</td>
            </tr>
        {% endif %}

        {% if form.phone %}
            <tr>
                <td valign="top">Телефон:</td>
                <td valign="top">{{ form.phone }}</td>
            </tr>
        {% endif %}

        {% if form.email %}
            <tr>
                <td valign="top">Эл. почта:</td>
                <td valign="top"><a href="mailto:{{ form.email|lower }}">{{ form.email|lower }}</a></td>
            </tr>
        {% endif %}

        {% if form.message %}
            <tr>
                <td valign="top">Сообщение:</td>
                <td valign="top">
                    <div style="font-style: italic; color:#8b8b8b;">{{ form.message }}</div>
                </td>
            </tr>
        {% endif %}
    </table>
</div>